name: Build LaTeX exercises as PDF

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  build_exercises:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository      
        uses: actions/checkout@v3

      - name: Compile LaTex documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            week_1.tex
            week_2.tex

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files:  |
            week_1.pdf
            week_2.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}